#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 1
#SBATCH --output=/volatile/halla/apex/full_replay/slurm/out/%x.%j.out
#SBATCH --error=/volatile/halla/apex/full_replay/slurm/err/%x.%j.err
#SBATCH --time=0:10:00

run=$1

hadd $VOLATILE_DIR/production/replay.$run.root $VOLATILE_DIR/production/replay.$run.*.root

rm $VOLATILE_DIR/production/replay.$run.*.root

