#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --mem-per-cpu 256
#SBATCH --job-name gen_tracks
#SBATCH --time 0:30:00


if [ $2 = "true" ]
then 
   analyzer -l -b -q 'vdc_logMethod_fork.C('$4', true,  '$1', "output_trees/tracks/part/new_R_'$5'", "replay/out", '$3')'
fi 

if [ $2 = "false" ]
   analyzer -l -b -q 'vdc_logMethod_fork.C('$4', false, '$1', "output_trees/tracks/part/new_L_'$5'", "replay/out", '$3')'
fi 
