#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task=4
#SBATCH --mem=7500M
#SBATCH --gres=disk:8G
#SBATCH --time 60
#SBATCH --output=/volatile/halla/apex/full_replay/slurm/out/%x.%j.out
#SBATCH --error=/volatile/halla/apex/full_replay/slurm/err/%x.%j.err

# set up APEX env
source set_apex_replay_env.sh
cd ${PATH_APEX_REPLAY}
echo "<${0}>: pwd: '$(pwd)'" 

PATH_SCRATCH="/scratch/slurm/${SLURM_JOB_ID}"

###################################################################################
#
# Ordered parameters:
#
run=$1
stem_decode_output="${PATH_SCRATCH}/decode"
stem_replay_output=$2
path_odef=$3
mode=$4

if [[ "${path_odef}~" == "~" ]]; then
    path_odef="outDefs/full_replay.odef"
fi

if [[ "${mode}~" == "~" ]]; then
    mode="both"
fi

n_rawfiles=$(ls -1 ${PATH_APEX_CACHE}/apex_$run.* 2>/dev/null | wc -l)

echo "<${0}>: $n_rawfiles files to decode"

part_d=-1 

paths_replay_input=""

for path_decode_input in $(ls -1 ${PATH_APEX_CACHE}/apex_$run.*)
do 
    part_d=$(($part_d + 1))
    
    path_decode_output="${stem_decode_output}.${run}.part-${part_d}.root"
    
    echo "<${0}>: PROCESSING decode $part ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
    echo "<${0}>: input:  $path_decode_input"
    echo "<${0}>: output: $path_decode_output"
    echo "<${0}>: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    cmd_string="decode_run.C(\"$path_decode_input\", \"$path_decode_output\", \"$path_odef\")"
    echo "command string: $cmd_string"
    
    time echo ".x ${cmd_string}" | analyzer
    	    
    echo "<${0}>: done with sub-file $part_d. ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
done


# assemble a comma-separated, quoted list of all input path(s)
paths_replay_input=""
while read -r line
do 
    #see if this is the first path. if so, then don't add a trailing comma
    if [[ "~${paths_replay_input}" == "~" ]]
    then
	paths_replay_input="\"${line}\""
    else
	paths_replay_input="\"${line}\", ${paths_replay_input}"
    fi
done < <(ls -w 0 ${stem_decode_output}.${run}.*)

#now, use our script to compile our replay code once, and then run all inputs.
cmd_string="replay_run_series.C(${run}, \"${stem_replay_output}\", {${paths_replay_input}}, \"both\")"

time analyzer -b -q "${cmd_string}" 

#echo "<${0}> hadd results together..."
#hadd -k -j $(nrpoc) ${stem_replay_output}.${run}.root ${stem_replay_output}.${run}.part#-* && rm ${stem_replay_output}.${run}.part-*

echo "<${0}> done." 

