#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --output=/volatile/halla/apex/full_replay/slurm/out/%x.%j.out
#SBATCH --error=/volatile/halla/apex/full_replay/slurm/err/%x.%j.err

# set up APEX env
source set_apex_replay_env.sh
cd ${PATH_APEX_REPLAY} 
echo "<${0}>: pwd: '$(pwd)'" 

###################################################################################
#
# Ordered parameters:
#
run=$1
stem_output=$2
path_odef=$3

n_rawfiles=$(ls -1 ${PATH_APEX_CACHE}/apex_$run.* 2>/dev/null | wc -l)

echo "<${0}>: $n_rawfiles files to decode"

part=-1 

for path_input in $(ls -1 ${PATH_APEX_CACHE}/apex_$run.*)
do 
    part=$(($part + 1))
    
    path_output="${stem_output}.${run}.part-${part}.root"
    
    echo "<${0}>: PROCESSING SUB-FILE $part ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
    echo "<${0}>: input:  $path_input"
    echo "<${0}>: output: $path_output"
    echo "<${0}>: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    cmd_string="decode_run.C(\"$path_input\", \"$path_output\", \"$path_odef\")"
    echo "command string: $cmd_string"
    
    echo ".x ${cmd_string}" | analyzer
    
    echo "<${0}>: done with sub-file $part. ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
done
    
