#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 20
#SBATCH --mem 4G 
#SBATCH --output=/volatile/halla/apex/full_replay/slurm/out/%x.%j.out
#SBATCH --error=/volatile/halla/apex/full_replay/slurm/err/%x.%j.err

# set up APEX env
source set_apex_replay_env.sh
cd ${PATH_APEX_REPLAY} 

###################################################################################
#
# Ordered parameters:
#
run=$1
stem_input=$2
stem_output=$3

n_inputs=$(ls -1 ${stem_input}.$run.* 2>/dev/null | wc -l)

echo "<${0}>: $n_inputs files to replay"

part=-1 

for path_input in $(ls -1 ${stem_input}.$run.*)
do 
    part=$(($part + 1))
    
    path_output="${stem_output}.${run}.part-${part}.root"
    
    echo "<${0}>: PROCESSING FILE $part ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~" 
    echo "<${0}>: input:  $path_input"
    echo "<${0}>: output: $path_output"
    echo "<${0}>: ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"

    cmd_string="vdc_track_replay.C(\"$path_input\", \"$path_output\", ${run}, \"both\", 0)"
    echo "command string: $cmd_string"
    
    echo ".x ${cmd_string}" | analyzer
    
    echo "<${0}>: done with sub-file $part. ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~"
done
    
