#!/bin/bash

#SBATCH --nodes 1
#SBATCH --partition production
#SBATCH --account halla
#SBATCH --ntasks 1
#SBATCH --cpus-per-task=4
#SBATCH --mem=5G
#SBATCH --gres=disk:2500M
#SBATCH --time 600
#SBATCH --output=/volatile/halla/apex/full_replay/slurm/full-replay/%x.%a.%A.out
#SBATCH --error=/volatile/halla/apex/full_replay/slurm/full-replay/%x.%a.%A.err

# move to the scratch dir 
PATH_SCRATCH="/scratch/slurm/${SLURM_JOB_ID}" 

FUNC="run-full-replay-array" 

# check to make sure this directory exists
if [[ ! -d "${PATH_SCRATCH}" ]]
then
    echo "scratch directory does not exist! path: ${PATH_SCRATCH}" >&2 
    exit 1 
fi

cd ${PATH_SCRATCH}

path_tarball=${1}
echo "<${FUNC}> [$(date +'%y-%m-%dT%H:%M:%S')]: In script." 
echo "<${FUNC}>: unpacking tarball: ${path_tarball}" 

# unpack the tarball of data / executables
tar -xzf ${path_tarball}

echo "<${FUNC}>: done." 

# set up APEX env
echo "<${FUNC}>: setting env"

source set_apex_replay_env.sh
echo "<${FUNC}>: pwd: '$(pwd)'" 

OUTPUT_DIR="${PATH_APEX_VOLATILE}/production" 

# load the proper version of the analyzer
#module unload analyzer 
#module load analyzer/1.7.15 

echo "<${FUNC}>: analyzer version:" 
analyzer --version

echo "<${FUNC}>: root version:" 
root --version

echo "<${FUNC}>: uname -a (OS info):"
uname -a



# check to make sure we have an 'array tasks' file 

PATH_TASK_LIST="array-tasks.csv"

if [[ ! -f "${PATH_TASK_LIST}" ]]
then    
    echo "Task file does not exist! expected rel. path: ${PATH_TASK_LIST}; directory contents: " >&2 
    ls -1 * >&2 
    exit 1 
fi

echo "<${FUNC}>: Starting timestamp: $(date +'%Y.%m.%d %H:%M:%S')" 

# now, execute all tasks: 
echo "<${FUNC}>: Executing task macro:"

# get list of all runs
runlist=$(./scripts/get_runs_in_task.sh "${PATH_TASK_LIST}" ${SLURM_ARRAY_TASK_ID})

if [[ -z "${runlist}" ]]
then
    echo "<${FUNC}>: no runs found for task: ${SLURM_ARRAY_TASK_ID}!!" >&2 
    exit 
fi

echo "<${FUNC}>: runs: "
echo "<${FUNC}>: ${runlist}" 

for RUN in ${runlist}
do
    echo "<${FUNC}> [$(date +'%y-%m-%dT%H:%M:%S')] executing run ${RUN}:" 

    analyzer -l -b -q "execute_specific_run.C(${RUN}, \"${PATH_TASK_LIST}\", \"${OUTPUT_DIR}\")"

done 
    
echo "<${FUNC}> [$(date +'%y-%m-%dT%H:%M:%S')]: Done." 
